### ISSUE TITLE
Add a config option for Desublimators so the rate to transfer items is per second and not per tick

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#13]
This would make then more configurable for lower speeds.

**Comment by SirStendec** [comment]
I've changed how rate limiting is handled for Desublimators in fe81a1c65c3630a5aef1a7bcb37db6f8729562e5. Now, rather than just items per tick, we have a concept of budget.

Machines add a certain amount to their budget per tick, capping at a maximum value. An item takes an amount of budget to transfer. For example, if an item takes 20 budget, and you gain 4 budget per tick, then it takes 5 ticks (or a quarter second) to gain enough budget to transfer an item, resulting in a transfer of four items per second.

These can be set with CraftTweaker via `budgetPerTick`, `maxBudget`, and `costPerItem`. Example:

```
var level = mods.wirelessutils.levels.get(1);
level.name = "Test";
level.budgetPerTick = 1;
level.maxBudget = 20;
level.costPerItem = 20;
```

If you want to play around with this a bit, there's a build on our Jenkins with it and everything else you've been requesting. https://jenkins.lord.moe/job/Wireless%20Utilities/56/

We should be releasing a new build on CurseForge at the end of this week, most likely. Let me know what you think and if I should tweak it at all before then.

**Comment by Insane96** [comment]
First off thanks for all the effort you put into my requests.

Second I'll definitely test the in dev build

**Comment by Insane96** [comment]
![2019-05-08_23 48 50](https://user-images.githubusercontent.com/7185104/57410719-df5a4880-71eb-11e9-8fa8-02adfbb3b869.png)
Uhm, some rounding might work here.
I would even suggest the otherway around to show the speed, in this case `1 item every 4.4s` or `4.4s per item`

**Comment by SirStendec** [comment]
New build is up that `s/Item` if there's less than one item per second. Also fixes the inventory saving issue you noticed. Thanks for all the reports.

https://jenkins.lord.moe/job/Wireless%20Utilities/57/

**Comment by Insane96** [comment]
I think that's pretty good
