### ISSUE TITLE
Shouldn't Block Augment need World augment to work?

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#17]
In the description it says "This augment allows desublimators to place and break blocks rather than [...] with a World augment". But you can't put both of them in a machine.

**Comment by SirStendec** [comment]
I can see how that text is a bit ambiguous. I'll clean it up. It is not intended that it needs a World Augment to work. I specifically stop players from being able to add both because it might make it a bit confusing what specifically is expected to happen.

I'd suggest that using a custom recipe with a World Augment in it would be a better choice if you want the Block Augment to be an *upgrade* from that. Thoughts?

And thanks again for opening so many issues. I'm pretty pumped honestly that someone is taking such a good look at the mod.

**Comment by Insane96** [comment]
> I'd suggest that using a custom recipe with a World Augment in it would be a better choice if you want the Block Augment to be an upgrade from that. Thoughts?

I'm really bad at making recipes, but maybe just put the World augment in the middle instead of the augment base.

> And thanks again for opening so many issues. I'm pretty pumped honestly that someone is taking such a good look at the mod.

Thank you for all the work you're doing.

**Comment by SirStendec** [comment]
I'm not going to change the default recipe, but it's definitely something for pack develops to consider. Anyways, I'm going to close this now too. The new info string should be more clear about the separation between the two augments.
