### ISSUE TITLE
Positional Condenser not placing water in world

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#18]
![2019-05-10_10 09 14](https://user-images.githubusercontent.com/7185104/57512475-0871fa80-730c-11e9-946a-fe2b786d4aa7.png)
![2019-05-10_10 11 58](https://user-images.githubusercontent.com/7185104/57512481-0e67db80-730c-11e9-84ad-b19a3c0beb51.png)

**Comment by SirStendec** [comment]
Condensers with World Augments only place / suck up fluid if their fluid rate is at least 1,000 mB/t, so they can do the whole thing in one tick. I'm guessing that's what you're running into?

I suppose I should add support for building up over a few ticks so that it will eventually collect those.

**Comment by SirStendec** [comment]
I just added support in 3f1b59274fbd343a7feacc6657fe9eadf4e5cdfd for burst capacity to Condensers so that they can actually place and drain fluids when their rate is under 1,000 mB/t. I'm assuming that this was the issue, so I'm going to close this now.

Please reply to this if it wasn't the problem and we'll reopen the issue.

**Comment by Insane96** [comment]
Definitely what I was thinking to accumulate the fluid until it's 1000mb and place it.
