### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by josephcsible** [SirStendec/WirelessUtilities#2]
Would you consider adding a license to this mod instead of having it be All Rights Reserved? I recommend LGPL if you want forks and other derivative works to have to be open-source, or MIT to basically let everyone do whatever as long as they credit you.

**Comment by Lordmau5** [comment]
As of right now we don't have any plans to switch from All Rights Reserved to a license such as MIT or LGPL.

We are, however, curious as to where CoFH's "Don't Be a Jerk" license is heading to, as I've asked King Lemming about the reuse of his license today to which he responded that he wants to refine it because in it's current state it's not what he wants it to be.

**Comment by josephcsible** [comment]
The CoFH DBaJ license is really no better than All Rights Reserved. Unless its meaning is significantly changed, it's not really worth switching to.
