### ISSUE TITLE
[Suggestion] A config option to make augments increase the energy requirement

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#24]
E.g. Applying a Crop augment would double the amout of energy required (or as flat value _x_ more energy)

**Comment by SirStendec** [comment]
Added in 594390de44e8fe2ca63ea4e89b9ecb3ca13acbab for all augments except Range, since that's kind of covered already by range costs.

Base Energy Per Operation = Base from Level * Augment Multipliers + Augment Additions

That should cover most things. I'm considering also adding an energy drain per tick, but this should be good for now.

**Comment by Insane96** [comment]
>  I'm considering also adding an energy drain per tick, but this should be good for now.

Would love this
