### ISSUE TITLE
[Enhancement] Desublimators with crop augment speed should scale with their speed

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#30]
The speed with it should break blocks / plant crops / harvest crops / plant sapling should be the same as it takes to transfer items.
E.g. a desublimator with speed of 2s/Item should break / plant a block (or a configurable amount of blocks like it's now) every 2 seconds. Or with a speed of 4 Items/s should break / plant 4 blocks per second (or one block every 0.25 secs)

**Comment by SirStendec** [comment]
I'm not sure how I want to handle this. Currently, Desublimators and Condensers will only do things that update the world directly on every 10th tick to avoid causing too many performance issues with constant updates.

There should be some sort of configuration rather than the hard coded number, I agree, but I don't want to just directly tie it to the individual machine's configured rate. Maybe put it as an extra value on levels? Thoughts?

**Comment by Insane96** [comment]
> Maybe put it as an extra value on levels? 

I think would be good

**Comment by SirStendec** [comment]
This is implemented now. Levels have a worldTickRate that defines how quickly a machine can possibly do stuff in the world. Additionally, each individual machine can be configured to wait anywhere between that minimum value and a maximum of 127 ticks. A GUI tab shows up to the left when applicable.
